### PR TITLE
Fix: Shutdown hub when transport is gone

### LINKED ISSUE #24: RedisTransport on close
Using the RedisTransport Pub/Sub, if there is an error in Redis resulting in a connection closure, there isn't a logic in place to perform a reconnection and potentially recycle the subscribe. I think we are missing a listener for $this->subscriber->on('close') in the RedisTransport's init(), and to handle this issue. We noticed this in practice, in our production environment. Whenever Redis crashes or reboots, Mercure becomes inconsistent and non-functional.

### PR DESCRIPTION
**Pull request by bpolaszek**
Fix #24 - Hub is not aware of redis connection losses

- Introduces a regular ping to Redis connection
- Whenever a ping fails, kill the hub

Unfortunately I was not able to set up an automatic reconnection.
Updates can be prevented from being published by returning a 503 error, but for subscriptions, I could not manage to :
- Stop the SSE
- Make it aware of a new redis connection

Killing the hub is the best I can do so far - a supervisor process (systemd, supervisor etc) should handle its respawn.

### CODE REVIEW

File: src/Hub/Transport/Redis/RedisTransport.php [hunk 1]
```diff
@@ -41,8 +44,24 @@ public function __construct(
...
+        }
+    }
+
+    /**
+     * @codeCoverageIgnore
+     */
+    private function ping(): void
+    {
+        try {
+            await($this->redis->ping()); // @phpstan-ignore-line
```
Comment (misaert) [inline src/Hub/Transport/Redis/RedisTransport.php:61]: I think it is an error to use `await` for the call of ping method of Redis. It is a synchronous response, right? In local tests, I had 502 from Caddy for `/.well-known/mercure?topic=*`. Without the `await`, it seems better.

Comment (misaert) [reply src/Hub/Transport/Redis/RedisTransport.php:61]: But it doesn't work anyway for mercure subscription.

Comment (misaert) [reply src/Hub/Transport/Redis/RedisTransport.php:61]: In fact, it is strange because `_call` of `Clue\React\Redis\Client` returns a `PromiseInterface`.

Comment (misaert) [reply src/Hub/Transport/Redis/RedisTransport.php:61]: It seems the promise is not always resolved or rejected. In https://github.com/clue/reactphp-redis/blob/fccbda7b168306a6acfe491059a58454464f2f42/src/Io/StreamingClient.php#L136, it emits an event without resolving or rejecting the promise.

With `await`, it seems to wait forever.

**Comment by bpolaszek** [comment]
I just added a commit - can you please try again with this fix? 
I assume it's already done but don't forget to configure `pingInterval` in your DSN for this to work.

File: src/Hub/Transport/Redis/RedisTransport.php (hunk 1 above)
Comment (bpolaszek) [reply src/Hub/Transport/Redis/RedisTransport.php]: Seems to work better with the traditional `then()` approach - see [ca716bf](https://github.com/bpolaszek/freddie/pull/25/commits/ca716bf3527a8a66ae5120e1ee3e4d5e37d02417)

**Comment by misaert** [comment]
I think I don't need to configure `pingInterval` because it is defined to `2` seconds by default, right?

The new commit seems to fix the issue :+1: 

But I think the changes on `src/Hub/Controller/PublishController.php` is unnecessary. WDYT?

**Comment by bpolaszek** [comment]
> I think I don't need to configure `pingInterval` because it is defined to `2` seconds by default, right?
> 
> The new commit seems to fix the issue 👍
> 
> But I think the changes on `src/Hub/Controller/PublishController.php` is unnecessary. WDYT?

Good news! 🎉 
IMO throwing an exception when publishing fails adds an extra layer of reliability as it does not require to wait for the ping to fail (if configured) to throw an error. Besides, this ensures that the hub does not respond with a 201 status when publishing actually failed. WDYT?
